### ISSUE TITLE
Cannot control tv

### ISSUE THREAD

**Issue by WimHe** [balmli/com.samsung.smart#1]
Installed the app and it detected the 2 year old Samsung QE65Q7FAM TV, wired to network, without problem.
But all control  buttons show some error:
Error sending  value (Invalid WebSocket frame: invalid status code 1005)
TV has software T-KTMDEUC-1262.0 BT-S 
Also the 2nd newer TV on WiFi network has some issue QE55Q7FNA with software T-KTM2DUEC-1202.3, BT-S (latest version)

**Comment by balmli** [comment]
I have (hopefully) a fix for that.  

In app store tomorrow, I hope :-)

**Comment by WimHe** [comment]
that error is gone but now each button i press the TV shows a popup asking me to allow Homey to control the TV. If i allow it, it does not execute the requested action eg channel up, if i press the button again, TV asks again to give homey permission.
once or twice i saw bb a network error too.
hope u can fix it, would love to use the app. Pleased to help debug it.

**Comment by balmli** [comment]
Hi,  

Have you checked the latest v. 1.0.5 in app store ?

Think it might be OK now..

**Comment by WimHe** [comment]
Yes I did. Now it's working   thanks. I like it very much, specially in a flow I can send any key. Would still be great if I could also do so from the device view. Not because it's very useful in daily use but just because I can test each key. There are so many in the menu while my remote only has a few, it's just nice to be able to test them without having to edit it into a flow.
But this is a great app. Thanks.

**Comment by balmli** [comment]
OK, I close the issue then.

Bu device view, I guess you mean the mobile app?   There's not much I can do about that..  That is Athom's design ..
