### ISSUE TITLE
Automatically refresh IP address

### ISSUE THREAD

**Issue by balmli** [balmli/com.samsung.smart#11]
Have a task that checks if the IP address for TV has been updated, and store in settings.

**Comment by PaddyPop** [comment]
Hi, will this be implemented - It would be REALLY useful as the flow crash everytime my TV or router is restarted. Thanks!

**Comment by balmli** [comment]
There's no good solution for discovery for the long list of Samsung models.

The best solution here is to reserve an IP in the router, or assign a static IP.
