### ISSUE TITLE
 Send key Power off does not work

### ISSUE THREAD

**Issue by Vincent75b** [balmli/com.samsung.smart#12]
On Samsung the frame 2018. Command might be different for this type of tv because of the ‘art mode’?

Tried it to give a 5 sec power off signal to turn the tv completely off

I can turn the tv on and in art mode from the app (icon) (and vice versa)

Send key Power Toggle does work!

**Comment by balmli** [comment]
See #10

**Comment by balmli** [comment]
I close this issue, since it's a duplicate of #10
