### ISSUE TITLE
Manual IP Address

### ISSUE THREAD

**Issue by Veldkornet** [balmli/com.samsung.smart#14]
My TV is on a different VLAN to Homey, so the automatic search will never find it. 

Could you add the option to manually enter the IP address of the tv? 

I have a UE32ES5700

**Comment by balmli** [comment]
Hi,

After around 30 seconds searching, and the TV will not be found, but you will get an option to add a TV anyway.

Add the TV, and then go to "Advanced settings", and you can enter the IP address.

**Comment by Veldkornet** [comment]
You’re right, that works. 

I was sure that I didn’t get that option yesterday when I tried... but it’s working now anyway, so issue solved. ;)
