### ISSUE TITLE
Polling interval min / Max blank 

### ISSUE THREAD

**Issue by Veldkornet** [balmli/com.samsung.smart#16]
App version: 1.5.0

When you go to change the polling interval, the values for the min and Max are blank

![9CC4B99F-B303-4C57-A30D-6B1903E6BEEE](https://user-images.githubusercontent.com/10297361/56845951-0d28be80-68c9-11e9-8644-b4ff6bbeb2d9.jpeg)

**Comment by balmli** [comment]
OK, thanks

I will look into it

**Comment by balmli** [comment]
Fixed in v. 1.6.0
