### ISSUE TITLE
Flow created to turn tv off keeps turning on tv

### ISSUE THREAD

**Issue by beker15** [balmli/com.samsung.smart#18]
I created a flow for my Samsung Smart TV. This flow is meant to turn the TV off in the event it is turned on between 6am and 2pm. This (of course) to regulate the time my children spend on watching TV. The cards are:
If: [TV] Samsung q6 series is turned on
And: Time is between 6:00 and 14:00
Then: [TV] Samsung q6 series Turn off.

The flow works but after a minute or so the TV switches on again, which triggers the flow to turn it off again. Somehow a loop is created. Any ideas on how to fix this?

I have no other flows concerning the TV and when I disconnect the power from the Homey directly after it turned my TV of the TV remains off.

**Comment by balmli** [comment]
The app checks constantly if the TV is on / off, by accessing the TV-interface.  

The TV-interface is also turned off when the TV is turned off, but after a delay.  On my TV this is about 20 seconds.   And sometimes the interface turns on, even if the TV is actually off.

So it is not easy for the app to know correctly if the TV is actually on or off.

The best solution for you might be to use a smart plug to turn the power completely off for the TV in the period.
