### ISSUE TITLE
App worked but not anymore

### ISSUE THREAD

**Issue by jw-bouma** [balmli/com.samsung.smart#19]
Ik used your app for my Samsung tv. It worked until recently. It doesn't see the status anymore. Also when i turn it off the app doesn't react. Something changed recently? My Samsung is from 2011.

**Comment by glasn** [comment]
+1 I can't control the TV anymore. This was working before. The detection on "TV on" and "TV off" is still ok. I removed and added the TV but that's not helping.

**Comment by balmli** [comment]
This is probably two different issues.. 

Check that the correct IP address for the TV is used.

**Comment by jw-bouma** [comment]
Thanks i reinstalled the tv and this solved the problem. The difference was
that you added a legacy tv that wasn't there before.

Thank you
Jan Willem

Op za 21 sep. 2019 13:16 schreef Bjørnar Almli <notifications@github.com>:
