### ISSUE TITLE
Ambient mode

### ISSUE THREAD

**Issue by Matt-Chid** [balmli/com.samsung.smart#22]
Hi
I had your app working to automatically put TV into Ambient mode by sendingbthe key Key_Ambient.

Since I noticee tou updated the app, I now have to choose from a list of keys. when I select Ambient it is now not working and the TV goes to HDMI2 instead.

As there now no option to manually set the key, I cannot get it to work.

Any ideas please?

Thanks

**Comment by Matt-Chid** [comment]
Am I asking in the correct place?

**Comment by balmli** [comment]
Hi,  Sorry for the slow response.

This is OK, or it is possible to use the community page: https://community.athom.com/t/app-samsung-smarttv/10019


Yes, the "KEY_AMBIENT" - key (Ambient mode) was added in 1.6.3, 17th March 2020.

You can use the "Send list of keys", with KEY_AMBIENT as input,
or you can use the "Send key" action, with "Ambient mode".

This will both lead to "KEY_AMBIENT" being sent.

If this does not work, can you try to send the key, and then press "Create diagnostics report", so I will receive a log, and might see what fails.

**Comment by Matt-Chid** [comment]
Thanks for the response

In my flow , for the device (TV) , it allows me to turn on the TV and then to select (from the list of keys) Ambient mode. This does not work. However, I cannot see any option to select “send list of keys”? This used to be there but is not now.

How do I do a diagnostics report for the flow?

Thanks

**Comment by balmli** [comment]
The "Send list of keys" is another action card.

**Comment by balmli** [comment]
Try this:

1) turn the TV on
2) create a separate flow with just send "Ambient mode" key
3) test the flow.

If you have a flow with both "turn on" and "send ambient mode" .. the send ambient mode action must wait some seconds ... for the TV to be online

**Comment by Matt-Chid** [comment]
Ok, will try that

My current flow does turn on, and then have a 5 sec wait before sending Ambient mode

**Comment by Matt-Chid** [comment]
Diag code as discussed

Thank you

008b917a-2df5-449b-846c-fc46bc2fade2

**Comment by balmli** [comment]
OK,

But did you test the simple flow, with just setting ambient mode ?

**Comment by Matt-Chid** [comment]
Yes, that did not work either.

It is very odd , as before you did the update, it was working perfectly.

**Comment by Matt-Chid** [comment]
Hi

I have also done exactly as you ask below

e366b99f-4b3d-432b-9de1-6dab04fb17ab

Still the same result I’m afraid.

**Comment by Matt-Chid** [comment]
Hi

Any update on this?

**Comment by balmli** [comment]
Nothing was changed from v. 1.6.3 to 1.7.1 that would stop Ambient mode from working.

Does sending other keys work OK ?

**Comment by Matt-Chid** [comment]
No, but it will turn on and off whic is odd.

Any ideas?

Sent from Samsung Mobile on O2

________________________________

**Comment by balmli** [comment]
Can you try to re-add the TV ?

**Comment by Matt-Chid** [comment]
Thanks, that has worked. Not sure why it should but it has. The TV has a fixed IP in the router ARP , so the IP had not changed.

Great to have it working. Thanks for help and for a great app.

Sent from Samsung Mobile on O2

________________________________

**Comment by balmli** [comment]
Glad to hear that!!
