### ISSUE TITLE
Error 1005 

### ISSUE THREAD

**Issue by hubbe74** [balmli/com.samsung.smart#23]
Get error 1005 all the time. Tried to set secure connection to true but it keeps going back to off.

**Comment by balmli** [comment]
Hi,

Can you try this link, when the TV is on, and send me the info:

http://<TV IP address>:8001/api/v2/

**Comment by hubbe74** [comment]
{"device":{"FrameTVSupport":"true","GamePadSupport":"true","ImeSyncedSupport":"true","OS":"Tizen","TokenAuthSupport":"true","VoiceSupport":"true","countryCode":"SE","description":"Samsung DTV RCR","developerIP":"0.0.0.0","developerMode":"0","duid":"uuid:81ec8fd5-d861-41e1-9325-5120d3ce828e","firmwareVersion":"Unknown","id":"uuid:81ec8fd5-d861-41e1-9325-5120d3ce828e","ip":"192.168.1.51","model":"17_KANTM_UHD","modelName":"UE43LS003","name":"[TV] Samsung Frame (43)","networkType":"wired","resolution":"3840x2160","smartHubAgreement":"true","type":"Samsung SmartTV","udn":"uuid:81ec8fd5-d861-41e1-9325-5120d3ce828e","wifiMac":"54:bd:79:74:67:e9"},"id":"uuid:81ec8fd5-d861-41e1-9325-5120d3ce828e","isSupport":"{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"true\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\"}\n","name":"[TV] Samsung Frame (43)","remote":"1.0","type":"Samsung SmartTV","uri":"http://192.168.1.51:8001/api/v2/","version":"2.0.25"}

Hälsningar
Daniel Svensson

7 maj 2020 kl. 07:53 skrev Bjørnar Almli <notifications@github.com>:

﻿

Hi,

Can you try this link, when the TV is on, and send me the info:

http://:8001/api/v2/

**Comment by balmli** [comment]
Hi Daniel,

Please install the test-version from this link:

https://homey.app/a/com.samsung.smart/test/

and tell me if it works now.


Thanks!

**Comment by balmli** [comment]
If you still have a problem, there is something wrong happening during the pairing process.

So then you can press the "Create diagnostics report" - button from the app - page in the mobile app, and I'll receive a log and might see the issue.

**Comment by hubbe74** [comment]
Nope, same issue

Hälsningar
Daniel Svensson

8 maj 2020 kl. 10:45 skrev Bjørnar Almli <notifications@github.com>:

﻿

If you still have a problem, there is something wrong happening during the pairing process.

So then you can press the "Create diagnostics report" - button from the app - page in the mobile app, and I'll receive a log and might see the issue.

**Comment by hubbe74** [comment]
86725030-292d-43a7-85a3-57b1d31bb069

Hälsningar
Daniel Svensson

9 maj 2020 kl. 17:57 skrev Daniel Svensson <svennas@hotmail.com>:

﻿ Nope, same issue

Hälsningar
Daniel Svensson

8 maj 2020 kl. 10:45 skrev Bjørnar Almli <notifications@github.com>:

﻿

If you still have a problem, there is something wrong happening during the pairing process.

So then you can press the "Create diagnostics report" - button from the app - page in the mobile app, and I'll receive a log and might see the issue.

**Comment by balmli** [comment]
I got the log.  Thanks.

**Comment by balmli** [comment]
Have you tested on the latest version?  V. 1.7.3 ?

**Comment by hubbe74** [comment]
Japp. Samma problem, jag har gett upp med appen. Jag kör nu Homeassistant och där funkar det perfekt!

Hälsningar
Daniel Svensson

11 okt. 2020 kl. 15:57 skrev Bjørnar Almli <notifications@github.com>:

﻿

Have you tested on the latest version? V. 1.7.3 ?
