### ISSUE TITLE
Launch app & launch browser doesn't work.

### ISSUE THREAD

**Issue by Tjadevisser** [balmli/com.samsung.smart#24]
Thanks for you application. 
Proud owner of the Samsung The Frame 32" 2020 model.
Unfortunately the Launch app & launch browser doesn't work.

I can control almost al functionality with the app like:
- Launch youtube video
- set input source (via smartthings api)
- send key

But the above options result in:
Launch app: app list is empty
Launch browser: executed but without visual result

Hopefully we can debug:)

Tom

**Comment by balmli** [comment]
Try this:

1. turn the TV on
2. restart the app (from app settings)
3. wait around 5 minutes
4. press the "Create diagnostics report"-button, and I will have a report

**Comment by Tjadevisser** [comment]
Thanks for your reply
Diagnostic: 4f910c07-714c-4022-9618-500505198fd1

**Comment by Tjadevisser** [comment]
Without being inpatient or rude.....
Did you find time to look at my issue?

**Comment by balmli** [comment]
Yes.  Looks like the app thinks the TV is on an unreachable network for this.

It is either an EHOSTUNREACH or an ENETUNREACH error code.

I think this is a situation for many TVs.

A solution would be to add static list of apps, if fetching the list of apps from the TV does not work.

I will fix this in an upcoming release.

**Comment by Tjadevisser** [comment]
Thanks for your help. Please let me know if i can test something for you.

**Comment by balmli** [comment]
This is solved in v. 1.7.5:

https://homey.app/a/com.samsung.smart/test/
