### ISSUE TITLE
Model UE55JU6740 fails to recieve command after turning power off/on.

### ISSUE THREAD

**Issue by sondreen** [balmli/com.samsung.smart#25]
Not sure why, this has happened since I started using the app.
The TV has a static IP, is added as encrypted and recieves commands without issues after adding it in Homey. When I add it in Homey it asks for a PIN which is successfully accepted. It won't accept commands to turn on, only times out. Therefore I tried using a smart plug for switching power, when I turn it on again Homey recieves updated power state, but the TV won't accept any new commands. It almost seems like it looses authorization to send commands when power is lost. It recieves commands without issue if I set the TV in standby by using the physical remote, but then the purpose of automating the process kind off goes away :(

It shows information on both /api/v2/ and /ms/1.0/. Firmware is updated and connected via WLAN. Have also tried adding as different modes without success. Diagnosis report created, 7ad5b70d-9dff-43f1-a83c-840fbe8a570b

**Comment by balmli** [comment]
The app uses Wake-on-LAN / Wake-on-WiFI.  If your model does not support Wake-on-LAN / Wake-on-WiFI it won't work ..

I don't think your JU-model support that, but I'm not 100 % sure.

**Comment by sondreen** [comment]
@balmli 
I might have explained myself badly or you've misunderstood, my issue was not pertaining to toggling power. I accepted that my TV most likely doesn't support WoL, therefore I started using a smart plug. The issue is that after toggling the power with the plug, the TV stops accepting commands sent.

**Comment by sondreen** [comment]
> The app uses Wake-on-LAN / Wake-on-WiFI. If your model does not support Wake-on-LAN / Wake-on-WiFI it won't work ..
> 
> I don't think your JU-model support that, but I'm not 100 % sure.
