### ISSUE TITLE
Model UE55JU6740 fails to recieve command after turning power off/on

### ISSUE THREAD

**Issue by sondreen** [balmli/com.samsung.smart#26]
Not sure why, this has happened since I started using the app.
The TV has a static IP, is added as encrypted and recieves commands without issues after adding it in Homey. When I add it in Homey it asks for a PIN which is successfully accepted. It won't accept commands to turn on, only times out. Therefore I tried using a smart plug for switching power, when I turn it on again Homey recieves updated power state, but the TV won't accept any new commands. It almost seems like it looses authorization to send commands when power is lost. It recieves commands without issue if I set the TV in standby by using the physical remote, but then the purpose of automating the process kind off goes away :(

It shows information on both /api/v2/ and /ms/1.0/. Firmware is updated and connected via WLAN. Have also tried adding as different modes without success. Diagnosis report created, 7ad5b70d-9dff-43f1-a83c-840fbe8a570b

The issue is that after toggling the power with the plug, the TV stops accepting commands sent.

**Comment by onehand** [comment]
I have the same issue with UE40JU6400

**Comment by balmli** [comment]
Can you re-pair with the new v. 2.0.x version ?

Install from this link:

https://homey.app/a/com.samsung.smart/test/
