### ISSUE TITLE
Condition card 'app is running' doesn't seem to work

### ISSUE THREAD

**Issue by mhoogenbosch** [balmli/com.samsung.smart#28]
See also: https://community.athom.com/t/app-samsung-smarttv/10019/375

With the condition card 'is app running' it doesn't seem to work. I created a card is app running netflix and with a action to pause the tv, but with the test button it just pauses, even though netflix isn't running. Tried it with prime too, and same issue.

**Comment by balmli** [comment]
This should be fixed in 1.8.3
