### ISSUE TITLE
Samsung TV Model UA48J5200 Not Working

### ISSUE THREAD

**Issue by hiato6** [balmli/com.samsung.smart#29]
Hi, I'm trying to add my UA48J5200 Samsung TV but I keep getting "TV not found, check  IP address" error. Tried the 3 type, Samsung TV, Encrypted and Legacy but none works.

Any idea what i'm doing wrong?

**Comment by balmli** [comment]
For J models, you must use the Encrypted driver.

And please test v. 2.0.x, and report back here:

https://homey.app/a/com.samsung.smart/test/
