### ISSUE TITLE
Power off 

### ISSUE THREAD

**Issue by Gosephe** [balmli/com.samsung.smart#3]
Good app, finally ip control. Power off not always working. Tv 2016. Other controls oke

**Comment by balmli** [comment]
I have the same issue my self, but I think that's a TV issue.  I also have a 2016 - model.

Some times the TV does not respond to the message from the app.

Would be nice if you could try to send the "Power off" key by using the "Send key" action, and see if that works..

**Comment by balmli** [comment]
BTW, for turning off the TV from the mobile app, or from the "Turn off" action, the "Power toggle" is used.

KEY_POWER: "Power toggle": used in the app.
KEY_POWER_ON: "Power on" -> some TVs respond to this, but only if in "light" standby mode
KEY_POWER_OFF: "Power off" -> some TVs respond to this

**Comment by balmli** [comment]
Closing this issue
