### ISSUE TITLE
TV seems to go "off" and "on" multiple times while off.

### ISSUE THREAD

**Issue by thorleifjacobsen** [balmli/com.samsung.smart#31]
I've put up an action "When TV Turns on" and "When TV turns off" which sends me a notification. This gets triggered about every 5 minutes with polling enabled even if the TV is off (black screen, red light)

Have the 2020 model of samsung the frame 55".

**Comment by balmli** [comment]
Yes, this is a known issue with the network interface of the Samsung TVs.

You can read about it in the community pages:
https://community.athom.com/t/app-samsung-smarttv/10019/329

**Comment by thorleifjacobsen** [comment]
Ok, so you would not consider doing a a different method of checking if TV was online other than smarthings,upnp and ping?

E.g. polling the http://<ip>:8001/api/v2/ gives a powerstate variable which states standby if it is just powered off. But it gives nothing while the TV is unreachable. 

I've tested quickly the 8001 port is still closed while pinging shows tv as online. So maybe an HTTP request with a 1 sec timeout would be a better check.

**Edit**
Using another samsung remote with keys you can turn on Virtual Standby which holds the TV online while it goes to standby and keeps the API running so "PowerState" is in "Standby" but the TV actually seems off. This is used for hospitality modes. So this is another workaround where you actually get the PowerState to check if tv is off / on. But for most users checking if the api respods would be a great indication of TV on/off . But if it gets a response it must check that powerstate != standby. Or else you would get more false positives. :)

**Another Edit**: 
Every time I get a notification that the TV is on I can open: http://10.0.20.109:8001/api/v2/

In there I see "PowerState=Standby". So instead of just checking if port is reachable maybe download it and see what powerstate reads? 

So 3 cases:

PowerState: standby = Off
PowerState: On = On
Not able to download the json object = Off

A tip would be to lowercase powerstate value as it seems to be uppercase on On but lowercase on Standby this might be different on different models.

**Comment by thorleifjacobsen** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/8550684/112633856-2b432480-8e3a-11eb-925e-6c98635c8dff.png">


<img width="1066" alt="image" src="https://user-images.githubusercontent.com/8550684/112633887-3433f600-8e3a-11eb-9349-3004cda26043.png">


<img width="992" alt="image" src="https://user-images.githubusercontent.com/8550684/112633900-38601380-8e3a-11eb-9df8-56b53122292f.png">


This fixed it for me. :)

**Comment by thorleifjacobsen** [comment]
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/8550684/112636491-73b01180-8e3d-11eb-9e1f-9af521a14052.png">

Looks like it is apiActive and ping who fails it. I'm gonna stick with only powerstate :D

**Comment by balmli** [comment]
Cool !  Very good, thanks!

This has been made with an older TV, with no PowerState field:

```
{
  "id": "uuid:xxxxx",
  "name": "[TV] Samsung 8 Series (55)",
  "version": "2.1.0",
  "device": {
    "type": "Samsung SmartTV",
    "duid": "uuid:xxxxx",
    "model": "16_JAZZM_UHD",
    "modelName": "UE55KS8005",
    "description": "Samsung DTV RCR",
    "networkType": "wired",
    "ssid": "",
    "ip": "192.168.20.17",
    "firmwareVersion": "Unknown",
    "name": "[TV] Samsung 8 Series (55)",
    "id": "uuid:xxxxx",
    "udn": "uuid:xxxxx",
    "resolution": "3840x2160",
    "countryCode": "NO",
    "msfVersion": "2.1.0",
    "smartHubAgreement": "true",
    "VoiceSupport": "true",
    "GamePadSupport": "true",
    "wifiMac": "xxxxxf",
    "developerMode": "0",
    "developerIP": "",
    "OS": "Tizen"
  },
  "type": "Samsung SmartTV",
  "uri": "http://192.168.20.17:8001/api/v2/",
  "remote": "1.0",
  "isSupport": "{\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\",\"DMP_available\":\"true\",\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"EDEN_available\":\"true\"}"
}
```

**Comment by balmli** [comment]
Can you provide your response ?

**Comment by thorleifjacobsen** [comment]
```
{
	"device": {
		"FrameTVSupport": "true",
		"GamePadSupport": "true",
		"ImeSyncedSupport": "true",
		"Language": "nn_NO",
		"OS": "Tizen",
		"PowerState": "on",
		"TokenAuthSupport": "true",
		"VoiceSupport": "true",
		"WallScreenRatio": "0",
		"WallService": "false",
		"countryCode": "NO",
		"description": "Samsung DTV RCR",
		"developerIP": "0.0.0.0",
		"developerMode": "0",
		"duid": "uuid:b35ea225-ccb6-43eaxxxx",
		"firmwareVersion": "Unknown",
		"id": "uuid:b35ea225-ccb6-43ea-xxxx",
		"ip": "10.0.20.109",
		"model": "20_NIKEM_FRAME",
		"modelName": "QE55LS03TAUXXC",
		"name": "[TV] Samsung The Frame (55)",
		"networkType": "wired",
		"resolution": "3840x2160",
		"smartHubAgreement": "true",
		"type": "Samsung SmartTV",
		"udn": "uuid:b35ea225-xxxx",
		"wifiMac": "bc:7exxx"
	},
	"id": "uuid:b35ea225-ccb6-xxxx",
	"isSupport": "{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"true\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\"}\n",
	"name": "[TV] Samsung The Frame (55)",
	"remote": "1.0",
	"type": "Samsung SmartTV",
	"uri": "http://10.0.20.109:8001/api/v2/",
	"version": "2.0.25"
}
```

**Comment by thorleifjacobsen** [comment]
Ok, so seems to be only a certain few that can use the powerstate variable then. That is kinda boring. Must be something else to check the real state of the system. 

E.g. on the "Frame" TV I have there is:

- Standby (TV off but reachable or not reachable)
- On (Frame mode, showing pictures, this is also "off" )
- On (In-use mode, where you see tv e.t.c.)

My thought to be able to turn on the lights above TV if the frame shows pictures. Then turn them off if i open anything but spotify. Seems like I need a custom modded app :P I'll have to have my own version of this maybe.

**Comment by balmli** [comment]
My 2016 KS - model does not have the PowerState variable, but my newer TU has.

So, if there's a PowerState variable, that variable should be used.

**Comment by thorleifjacobsen** [comment]
Yes, seems like there must be implemented more logic to the "pullMethods" thing.

psudo:

```
let tvOn = false;

# Run API call

if (responseCode = 200) {
  if (response.client.powerState != undefined) {
    // TV with powerstate, lets use it to assume state.
    tvOn = response.client.powerState.toUpperCase() == "ON" ? true : false;
  } else {
   // Other TV's without powerState, lets assume it is online now
    tvOn = true
  }
}

return tvOn;
```

But there will be problem the way it is made now. As it seems to be just accepting any who is true. So ping might be true while the aPI call fails.  So it must have some kind of memory on what method works for that integrations. (?) Well. I'm just throwing out ideas. The change I did works perfectly for my TV (always pull with API).

Maybe that can be an option for the TV; Pull Method to use: PowerState / PING / UnPn / API Port

**Comment by mhoogenbosch** [comment]
I can confirm, i've got the powerstate too:

{
  "device": {
    "FrameTVSupport": "false",
    "GamePadSupport": "true",
    "ImeSyncedSupport": "true",
    "Language": "nl_NL",
    "OS": "Tizen",
    "PowerState": "on",
    "TokenAuthSupport": "true",
    "VoiceSupport": "true",
    "WallScreenRatio": "0",
    "WallService": "false",
    "countryCode": "NL",
    "description": "Samsung DTV RCR",
    "developerIP": "0.0.0.0",
    "developerMode": "0",
    "duid": "uuid:6962b9ec-22763d7e8ee",
    "firmwareVersion": "Unknown",
    "id": "uuid:6962b9ec-22767e8ee",
    "ip": "192.168.21.17",
    "model": "20_NIKEM_8K",
    "modelName": "QE75Q800TALXXN",
    "name": "[TV] Samsung Q800 Series (75)",
    "networkType": "wired",
    "resolution": "7680x4320",
    "smartHubAgreement": "true",
    "type": "Samsung SmartTV",
    "udn": "uuid:6962b9ec-32863d7e8ee",
    "wifiMac": "98:06:3c:a1:54:b4"
  },
  "id": "uuid:6962b92863d7e8ee",
  "isSupport": "{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"false\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\"}\n",
  "name": "[TV] Samsung Q800 Series (75)",
  "remote": "1.0",
  "type": "Samsung SmartTV",
  "uri": "http://192.168.21.17:8001/api/v2/",
  "version": "2.0.25"
}

There is btw an message in my TV screen allowing my device to connect, don't believe i've seen that before when it updates the power state. Maybe worth to mention on a changelog or even during adding the tv as device. Don't know for sure, but maybe it is the same permission when trying to use homey to control the volume up / down kinda buttons. Don't know.

**Comment by balmli** [comment]
TVs with "PowerState" should be OK.
