### ISSUE TITLE
Can't connect Samsung TV - UE50RU7100

### ISSUE THREAD

**Issue by aCrazyAfro** [balmli/com.samsung.smart#33]
![IMG_8443](https://user-images.githubusercontent.com/84179965/119239568-408eb380-bb4a-11eb-9b6f-17ebef990bea.JPG)
Is this TV compatible? I tried all the IP-adressen that are on my TV screen from the network settings.

I selected the Samsung (encrypted) if i look at the remote control on homey.app.

**Comment by balmli** [comment]
Please test v. 2.0.x, and report back here:

https://homey.app/a/com.samsung.smart/test/
