### ISSUE TITLE
only TV ON-command works

### ISSUE THREAD

**Issue by BasJ83** [balmli/com.samsung.smart#34]
The Homey Samsung Smart TV app has worked fine for months, but since the update to Homey 6.1 I am experiencing issues. When the TV is off, I can perform a power-on command succesfully via Homey. However, any other command, (key_send, run app, volume control, Power_off) results in an "unknown error", "Network request failed" of "[object][object]" error message. 
I am running Homey v 6.1.0 and app 1.8.3. The TV is a Samsung 65Q95T, which has worked fine with the app until this issue

**Comment by balmli** [comment]
Please test the new v. 2.0.0 version:

https://homey.app/a/com.samsung.smart/test/

and report back here.  You might need to re-pair the TV.

Also check that you have reserved an IP address in your network / Wi-Fi router for the TV.
