### ISSUE TITLE
Tv go on after 2uur

### ISSUE THREAD

**Issue by eeckelaertyannick** [balmli/com.samsung.smart#36]
94ad5010-208d-44d4-800c-423cfca8ee50

App starts my tv Every 2hours than my hue lamps go on because of the flow i set up. 

Extra question in the setting There is a Button frame tv... what is the function?

Thx!

**Comment by balmli** [comment]
If your TV support "PowerState", you should be fine. 

You can check your TV with the following link, but with your IP:

http://192.168.1.10:8001/api/v2/

and see if you find "PowerState".
