### ISSUE TITLE
SmartTV homey app stops working

### ISSUE THREAD

**Issue by FeKik** [balmli/com.samsung.smart#37]
I installed and set up the app with tv. It went really well for few days, but then suddenly stopped working. No flow works anymore.

**Comment by balmli** [comment]
Have you reserved an IP in your Wi-Fi router for the TV? 

Your TV will, as other devices in your network, receive a new IP address from the DHCP server in your Wi-Fi router, and when that changes the app does not know the correct IP address anymore.

So, reserve an IP address or assign a static IP address in the TV settings.  Then you can add the TV again

**Comment by FeKik** [comment]
Hi, I have static IP on my TV. I have found out that flow to turn on tv does not work. I can turn it off via flows, but mot turn on. This happened recently, since it worked for me.
