### ISSUE TITLE
Power State puling

### ISSUE THREAD

**Issue by eeckelaertyannick** [balmli/com.samsung.smart#38]
Tv activate Every 10sec to check power State. I have a flow wen tv is on the lamps go on. The power State Puling setting activate's the lamps Everry 10sec. Please give a solution for This thx!

**Comment by ThomasWi** [comment]
Since the last update the status for my TV on and off doesn't work anymore.... which also makes some of my flows not working. Before there has been no issues like this ever. Please fix. Thanks.

**Comment by Ironbeagle84** [comment]
Same issue, I can control the TV from homey, if I do that the power state is updated and flows run. But if I use the remote control the homey doesn't get the power state update.

**Comment by Elmago27310** [comment]
Bonjour,
Est ce que quelqu'un a une solution pour ce problème  ?

**Comment by eeckelaertyannick** [comment]
No pas deja :(

**Comment by balmli** [comment]
Please check v. 2.0.1

https://homey.app/a/com.samsung.smart/test/
