### ISSUE TITLE
Muting

### ISSUE THREAD

**Issue by jahnkenneth** [balmli/com.samsung.smart#4]
Hello,
When using the TV remote to mute the TV, this is not mirrored in the homey app. It still shows as unmuted. 
Any way of fixing this?

I have a flow that i want to mute the TV, but only if it is not muted allready...

**Comment by balmli** [comment]
Hi,

Things you do with the remote, is not easy to check from the app..  

Now it checks if the TV is on/off, and you have conditions ("and" in the flow) for checking if the TV is on, and if an app is running.

Would be nice to get the state for volume, muted / not muted.  And also the list of channels, maybe.

But I haven't found any way to get this information, and I don't think it's possible ..

But please help with the Googling :-)

**Comment by balmli** [comment]
Might add uPNP - support to the app, and that might work for some TVs to get the state.

Closing this issue now.
