### ISSUE TITLE
Direct source selection not working on Samsung UE46D7000

### ISSUE THREAD

**Issue by GibStorm** [balmli/com.samsung.smart#41]
I have an older Samsung UE46D7000. It's connected fine to Homey Pro, but I just cannot make the direct source selections work. Example; I want to select HDMI1 directly, so I set it to send that key. Doesn't work.

Using the "SOURCE" button works fine, but I cannot use "UP" and "DOWN" to control it with, either.

**Comment by Plantje1978** [comment]
I have the same issue with a similar TV

**Comment by balmli** [comment]
Have you tried HDMI (not HDMI1, 2 etc) ?

HDMI1, HDMI2, etc. does not work either on my UE55KS8005 either.

**Comment by Plantje1978** [comment]
Don't know why this is closed....
If I use "HDMI" it cycles through the HDMI inputs and that way, I can never be sure what HDMI source exactly is selected. I want to use this to trigger my "Home Alone" scene. So, I will typically not be around to check if the right HDMI source is chosen.
Is there a way to create a flow that switches to the correct input?

**Comment by balmli** [comment]
@Plantje1978  I see, but there's nothing I can do about this.  

It's a "feature" of your Samsung TV, I'm afraid.

**Comment by GibStorm** [comment]
It does not work. Why would you close the issue, when it is not fixed?

**Comment by Plantje1978** [comment]
I have a work around...
I created a flow that first sends the key "source"
Then I send the key "left" for multiple times. Just enough to be 100% sure it is focused on the most left source.
Then I send this many "right" keys until I am at the required source. Next, "enter" and finally "exit"

**Comment by balmli** [comment]
@GibStorm 

See the comment above why it's closed.

**Comment by Plantje1978** [comment]
So, this is just an event that is not available through the Samsung API? Too bad. Can I get some sort of notification if this is added?
