### ISSUE TITLE
Missing App in App Launcher

### ISSUE THREAD

**Issue by rvisser888** [balmli/com.samsung.smart#42]
Hello,

Is there a way to get an new-App into the selectionlist.

Missing app: IPTV Smarters Pro

Thanks for the answer

**Comment by Aymen53** [comment]
🔴🔴 Meilleur IPTV 📺 12 mois Confiance et garantie ✅  voulez essayer le test Atlas Pro, QHDTV, Volka, Neo, iron pro.., ou tout autre serveurs WtsApp: +213655135904

**Comment by rvisser888** [comment]
I think, this is not the answer we all want!!

**Comment by balmli** [comment]
Check the new v. 2.0.x version:

https://homey.app/a/com.samsung.smart/test/
