### ISSUE TITLE
Add a "Art mode" card for the frame tv

### ISSUE THREAD

**Issue by nicophili** [balmli/com.samsung.smart#44]
Hi,

Could you add a card to put the tv on art mode instead of switching it off ?

Best regards,

Nicolas

**Comment by Misterkimj** [comment]
I second this. Apps launching could be used to start a flow, but I can't find a way to start a flow when done using the TV. Any plans to add this card?

**Comment by balmli** [comment]
Noted, but cannot promise anything.

Please report any new requests in the community page:
https://community.athom.com/t/samsung-smarttv-app/10019
