### ISSUE TITLE
Amazon Prime Video App - Application not found

### ISSUE THREAD

**Issue by VenominousX** [balmli/com.samsung.smart#48]
Hi,
first of all, thank you for your great app. :)
I get an "Application not found" error when i check the Prime Video app is running on my Samsung Smart TV. I am using the app from the flowcards applist. Maybe caused by the dialId? It would be fantastic if you can fix this issue.

I need this function to store the running app to a variable and trigger the app start on my other tv in another room on room change.

![image](https://user-images.githubusercontent.com/66132770/182792128-6ad93afc-b8c3-4ce4-82f3-f58637a90135.png)

With best regards

**Comment by balmli** [comment]
Please check the new v. 2.0.x version, and see if that works better.

https://homey.app/a/com.samsung.smart/test/

BTW, there are two Prime TV apps now, so you might check the one called "Prime Video 2".
