### ISSUE TITLE
Samsung QE75Q75AATXXC cannot connect 

### ISSUE THREAD

**Issue by theAnton81** [balmli/com.samsung.smart#49]
Samsung QE75Q75AATXXC

Hello, I am trying to connect my TV to my Homey, but it is not found by the app and manually typing the IP does not work either. I have turned on external control on the TV and clicked Allow on the pop-up. Is this one of the TVs not supported, and if so, are there any plans to support it in the future?

With best regards
Anton

Update: Forgot to mention that I used the Encrypted option.

**Comment by balmli** [comment]
Encrypted is not the correct device for your TV.

Use the "Samsung" option.
