### ISSUE TITLE
TV is not responding

### ISSUE THREAD

**Issue by glasn** [balmli/com.samsung.smart#5]
Hi,

My TV wasn't detected automatically. I had to add the ip-address in the App. The TV is not responding to the Homey App instructions.

My TV details:
{
  "id": "07270e01-0078-1000-8cd0-5056bf7d0220",
  "name": "[TV] Living room",
  "version": "2.0.24",
  "device": {
    "type": "Samsung SmartTV",
    "duid": "07270e01-0078-1000-8cd0-5056bf7d0220",
    "model": "14_X14_BT",
    "modelName": "UE46H7000",
    "description": "Samsung TV RCR",
    "networkType": "wireless",
    "ssid": "Ziggo0851484",
    "ip": "192.168.178.10",
    "firmwareVersion": "Unknown",
    "name": "[TV] Living room",
    "id": "07270e01-0078-1000-8cd0-5056bf7d0220",
    "udn": "07270e01-0078-1000-8cd0-5056bf7d0220",
    "resolution": "1920x1080",
    "countryCode": "NL",
    "msfVersion": "2.0.24",
    "smartHubAgreement": "true",
    "developerMode": "0",
    "developerIP": "0.0.0.0"
  },
  "type": "Samsung SmartTV",
  "uri": "http://192.168.178.10:8001/api/v2/"
}

thanks for the help.

**Comment by balmli** [comment]
Is the Homey on the same network?  192.168.178.xxx ?

You can test http://192.168.178.10:8001/api/v2/ from your browser.

And press the "Create Diagnostics Report" from the mobile app.

**Comment by glasn** [comment]
Yes, it’s on the same network.

See: 7010a9e1-83e8-4f94-bfc9-e02067da29fe

**Comment by balmli** [comment]
The log looks good, no errors there.

Have you tried "Secure connection" from advanced settings ?

**Comment by glasn** [comment]
Yes tried that... no improvement. Though the “secure connection” setting is automatically deactivated. The TV supports http://192.168.178.10:8001/api/v2/ but it’s quit an old model. I think the model is 4+ years old.

**Comment by balmli** [comment]
You could try the "samsungctl" tool -> https://github.com/kdschlosser/samsungctl

Requires python on your PC.

And if that works,  it should be possible to find a solution for the app too.

**Comment by balmli** [comment]
Try adding a request on 
https://community.athom.com/t/samsung-smarttv-app/10019

Closing this issue.

**Comment by balmli** [comment]
See issue #9
