### ISSUE TITLE
Re-connect seamlessly when new IP

### ISSUE THREAD

**Issue by PaddyPop** [balmli/com.samsung.smart#52]
Hi, would it be possible to somehow fix when a TV gets a new IP?
Today, you have to log and watch the flows for the TV and then manually change the TV IP in Homey settings.

Thanks, I love the app!

**Comment by balmli** [comment]
Reserve an IP in your network / Wi-Fi router for the TV to avoid this issue.

This is a good choice for most IoT devices you connect to your Homey.
