### ISSUE TITLE
Sdk3 update gives error

### ISSUE THREAD

**Issue by jeroen1973** [balmli/com.samsung.smart#53]
Met de laatste update naar sdk3 krijg ik nu bij een samsungtv de error:  This.getDriver is not a function

**Comment by jeroen1973** [comment]
![Uploading 9E59B109-C59A-4E8C-BED2-3D9C3DE5BF7D.png…]()

**Comment by jeroen1973** [comment]
![501197ED-FD7C-41CC-88B7-987B825B7B91](https://user-images.githubusercontent.com/29982887/208724784-776dd5a1-0e02-44a4-b26a-0644649d7323.png)

**Comment by balmli** [comment]
Thank you for reporting!

This is for the "Samsung (encrypted)", right? 

(English, please :-) )

**Comment by balmli** [comment]
Please test v. 1.9.2 by installing from this link:

https://homey.app/a/com.samsung.smart/test/

**Comment by jeroen1973** [comment]
Yes it for the encrypted Samsung tv. The testversie 1.9.2 does the trick! Thanks for the great work

**Comment by balmli** [comment]
OK!   So you're able to control the TV by the app ?

**Comment by jeroen1973** [comment]
No, it only shows it’s on or of but then givers error when wanting to control it
![Uploading 6DD28865-DFF4-4CBE-B2BD-A986F48387C8.png…]()

**Comment by jeroen1973** [comment]
![Uploading 97745693-2D36-4868-836B-66FEF7A0EC28.png…]()
