### ISSUE TITLE
2 requests

### ISSUE THREAD

**Issue by gdroos68** [balmli/com.samsung.smart#6]
So happy that there is finally an app which can control my Samsung tv. I do have 2 requests
- My QE65Q7 can not be switced on by your app so i use wake on lan. It would be nice if you could incorperate this in your app
- HDMI1 to 4 do not work. Maybe you could also include a free text fiels.

**Comment by balmli** [comment]
The app has wake-on-lan / wifi, when you turn on.

Do you have a “Allow mobile devices to turn on the TV” - setting on your TV?  Maybe check that.

What solution do you use for wake-on-lan ?

In the next version, v. 1.2.0, it will be possible to add a list of fields for any key.

**Comment by balmli** [comment]
Try sending KEY_EXT20 before KEY_HDMI. / KEY_HDMI1..4

With v. 1.2.0 you can send a list of keys, with a shorter delay, for faster operation.

Closing this issue now.
