### ISSUE TITLE
not any command works

### ISSUE THREAD

**Issue by mennetalsma** [balmli/com.samsung.smart#7]
don't work on a UE40JU6000 it finds the tv, it connects.. but buttons and commands don't work network errors and time-outs.. shame.. #sad

on legacy mode it don't find the tv at all, and manualy setting the IP results in a error 

what up?

my TV is new enough, it responds to
http://192.168.X.X:8001/api/v2/
it gets me a nice Json reponse

{
"id": "uuid:6ffc1a15-5f4e-4268-baf7-20c94cf71c6e",
"name": "[TV] Korova TV",
"version": "2.0.25",
"device": {
"type": "Samsung SmartTV",
etc
etc

what am i doing wrong?

**Comment by balmli** [comment]
Yes, I see there is a class of TVs that respond to port 8001, but does not respond to the app.

You can check the community pages:
https://community.athom.com/t/samsung-smarttv-app/10019

And you can press the "Create diagnostics report" - button, and a will get an email, and may be able to help you.

**Comment by balmli** [comment]
Closing this issue now,

**Comment by mennetalsma** [comment]
Sorry to bother you again, but i you asked for the diagnostics report in an e-mail. But i dont have your e-mail adres.
So i’ll just post it here...

86bbabb6-1943-48a7-b652-627da70f3453
Hope you can help.. the community is a bit quiet on the issue
Grtz
Menne

**Comment by balmli** [comment]
See issue #9.
