### ISSUE TITLE
TV Goes on and off, only in app

### ISSUE THREAD

**Issue by coenboomkamp** [balmli/com.samsung.smart#8]
Hi Bjørnar!

Great app, thnx for that! Just got an issue that in the app it goes on and off. The actual TV does not. (QE55Q8F - 2018)
![IMG_1726](https://user-images.githubusercontent.com/34875500/54464170-db72f280-4775-11e9-821f-e891bca90db0.PNG)

Now my Sonos and the Homey LED go on and off all the time, quite annoying lol.
<img width="332" alt="Schermafbeelding 2019-03-15 om 22 59 28" src="https://user-images.githubusercontent.com/34875500/54464233-17a65300-4776-11e9-8abb-4cf4085c7745.png">
<img width="320" alt="Schermafbeelding 2019-03-15 om 22 59 36" src="https://user-images.githubusercontent.com/34875500/54464234-17a65300-4776-11e9-9842-24166b7deda0.png">

Any ideas?
Thnx,

Coen

**Comment by balmli** [comment]
The app checks the Enternet / WIFI - device of the TV, if it can get a response.  And if that's so.. it thinks that the TV is on.   

I see the same on my TV, that it respons on port 8001, even if it is actually off.

I am considering adding a Toggle switch in 'Advanced settings', so you can turn off this polling..
But the point of the polling is to see when the TV is turned on/off by the normal remote...

I am glad to have any suggestions how to solve this :-)

**Comment by treecamp** [comment]
Can you explain this polling a bit more? Sorry don't have any suggestions on how to solve this.
I do experience that after 2 / 3 times it's fine. Meaning the Homey app says the TV goes off, and on for 2 to 3 times, then it ends in the correct state, same as the TV.

**Comment by balmli** [comment]
The polling checks every 10 seconds if the TV responds to a HTTP request on http:// ip-address :8001/api/v2/ 

And the point of the polling is to see if the TV is on or off.  

Maybe a bit more complex algorithm or checking other endpoints might fix this.

**Comment by treecamp** [comment]
Just did a quick test, the url is not reachable when the TV is off. I'll do some more testing to see if i can find out anything.

**Comment by balmli** [comment]
Check the URL several times right after you have turned off the TV.

**Comment by treecamp** [comment]
Yes, then it's still reachable for a little while. When the TV is off, the URL is not reachable of course. When you turn on the TV, the URL is reachable instantly. When you turn off the TV, it takes a while for the TV to lose connection. Maybe we should change the polling to 30 seconds?

**Comment by balmli** [comment]
Thinking about adding a polling interval in adv. settings.  So it will be possible to change, and disable, the polling.

So you will be able to test other intervals yourself.

**Comment by treecamp** [comment]
I "solved" it by disabling the on and off flows for 5 minutes.

On Flow
WHEN
TV on

AND
WK - TV = no

THEN
WK - TV = yes
Turn off Homey LED Ring
Pause Sonos
Log

Off Flow
WHEN
TV off

AND
WK - TV = yes

THEN
WK - TV = no
Turn on Homey LED Ring
Play Sonos
Disable TV on flow
Disable TV off flow
Start timer TV 300 seconds
Log

Timer Flow
WHEN
Timer reached 0 

THEN
Enable TV on flow
Enable TV off flow
Log


![On](https://user-images.githubusercontent.com/34875500/55287887-61667e80-53af-11e9-8e57-f3dfca5a9083.jpg)
![Off](https://user-images.githubusercontent.com/34875500/55287888-63304200-53af-11e9-9640-d3c936078041.jpg)
![Timer](https://user-images.githubusercontent.com/34875500/55287889-675c5f80-53af-11e9-999a-dbe1f52eeedc.jpg)

**Comment by balmli** [comment]
That's good to hear !

**Comment by balmli** [comment]
In v. 1.4.0 there will be a 'Polling interval for TV status (s)' setting in  Advanced settings, so the polling interval can be increased to e.g. 30 secs.
