### ISSUE TITLE
Support for H, HU, J, JU, JS models

### ISSUE THREAD

**Issue by balmli** [balmli/com.samsung.smart#9]
H, HU, J, JU and JS models from 2014 and 2015 uses encrypted websocket communication, and is not supported in the current version, v. 1.2.0, of the app.

**Comment by glasn** [comment]
Any plans to support these models? Would be really great 😀.

**Comment by balmli** [comment]
Well, need alpha-testers..

https://community.athom.com/t/samsung-smarttv-app/10019/69

**Comment by balmli** [comment]
Respond here to participate in the alpha-testing:
https://community.athom.com/t/samsung-smarttv-app/10019

The first alpha-version will be available within a few days.

**Comment by balmli** [comment]
First version in app store now

**Comment by balmli** [comment]
Beta - version v. 1.3.0 ready in app store now

**Comment by glasn** [comment]
Tried it but the homey can’t find my tv. After 2 seconds the message comes with ‘no samsung tv’s found’.
39b359a6-b21b-41f4-938b-192866846e2f

**Comment by balmli** [comment]
https://community.athom.com/t/samsung-smarttv-app/10019

**Comment by balmli** [comment]
If you have a H/HU/J/JU/JS - model, the "Samsung (encrypted)" must be used.
